spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lawfirm
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public

# 应用配置
app:
  cors:
    allowed-origins: 
      - http://localhost:5173
      - http://localhost:3000

# MinIO配置
minio:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: lawfirm-archive